// Shared print/PDF helper for the module drawers. Builds a clean one-pager in
// a new window from a typed block model and calls the browser's print dialog
// (users save as PDF from there). All content is HTML-escaped - records hold
// free text.

export type PrintBlock =
  | { kind: "rows"; heading?: string; rows: [string, string][] }
  | { kind: "text"; heading: string; body: string }
  | { kind: "list"; heading: string; items: string[] }
  | { kind: "table"; heading?: string; columns: string[]; rows: string[][] };

export type PrintDoc = {
  title: string;
  meta?: string;
  banner?: string;
  blocks: PrintBlock[];
  disclaimer?: string;
};

const esc = (s: string) =>
  s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

const STYLE = `
  body{font-family:system-ui,-apple-system,sans-serif;color:#111;margin:0;
    padding:2.5rem;max-width:760px}
  h1{font-size:22px;margin:0 0 2px}
  .meta{color:#555;font-size:13px;margin:0 0 20px}
  .banner{border:1px solid #d9b430;background:#fdf6dc;padding:8px 10px;
    font-size:12px;font-weight:600;margin:0 0 16px;border-radius:6px}
  h2{font-size:13px;text-transform:uppercase;letter-spacing:.05em;color:#666;
    margin:20px 0 6px}
  p{font-size:14px;line-height:1.55;margin:0;white-space:pre-wrap}
  dl{margin:0;font-size:14px}
  .row{display:flex;justify-content:space-between;gap:16px;
    padding:5px 0;border-bottom:1px solid #eee}
  .row dt{color:#666}
  .row dd{margin:0;text-align:right}
  ul{margin:0;padding-left:18px;font-size:14px;line-height:1.6}
  table{width:100%;border-collapse:collapse;font-size:13px}
  th{text-align:left;color:#666;font-weight:600;padding:6px 8px;
    border-bottom:1px solid #ccc}
  td{padding:6px 8px;border-bottom:1px solid #eee;vertical-align:top}
  .footer{margin-top:28px;color:#777;font-size:11px;border-top:1px solid #ddd;
    padding-top:10px}
`;

function renderBlock(b: PrintBlock): string {
  const heading =
    "heading" in b && b.heading ? `<h2>${esc(b.heading)}</h2>` : "";
  if (b.kind === "rows") {
    const rows = b.rows
      .map(
        ([k, v]) =>
          `<div class="row"><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`,
      )
      .join("");
    return `${heading}<dl>${rows}</dl>`;
  }
  if (b.kind === "text") return `${heading}<p>${esc(b.body)}</p>`;
  if (b.kind === "list") {
    const items = b.items.map((i) => `<li>${esc(i)}</li>`).join("");
    return `${heading}<ul>${items}</ul>`;
  }
  const head = b.columns.map((c) => `<th>${esc(c)}</th>`).join("");
  const body = b.rows
    .map((r) => `<tr>${r.map((c) => `<td>${esc(c)}</td>`).join("")}</tr>`)
    .join("");
  return `${heading}<table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>`;
}

/** Opens the composed document in a new window and triggers print. */
export function printDocument(doc: PrintDoc): void {
  const w = window.open("", "_blank");
  if (!w) return;
  const generated = new Date().toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
  w.document.write(`<!doctype html><html><head><title>${esc(doc.title)}</title>
    <style>${STYLE}</style></head><body>
    <h1>${esc(doc.title)}</h1>
    ${doc.meta ? `<p class="meta">${esc(doc.meta)}</p>` : ""}
    ${doc.banner ? `<div class="banner">${esc(doc.banner)}</div>` : ""}
    ${doc.blocks.map(renderBlock).join("")}
    <div class="footer">Generated by Jojan One on ${generated}.${
      doc.disclaimer ? ` ${esc(doc.disclaimer)}` : ""
    }</div>
  </body></html>`);
  w.document.close();
  w.focus();
  w.print();
}
