import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import {
  useCoreData,
  upsertRisk, acceptRisk, closeRisk, reopenRisk, deleteRisk, newRiskDraft,
  completeMitigation, addMitigation,
  createConversation, appendMessage,
} from "@/data/store";
import { riskMetrics } from "@/data/cg-selectors";
import { formatDate } from "@/data/selectors";
import type { Risk, RiskCategory, RiskResponse } from "@/data/types";
import {
  Button, Card, Field, Input, Textarea, SectionHeader,
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/business/shared";
import { MetricCard } from "@/components/core/MetricCard";
import { EmptyState } from "@/components/core/EmptyState";
import { DetailDrawer } from "@/components/core/DetailDrawer";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { AlertTriangle, Plus, MessageSquare, Printer, RotateCcw, Check, HelpCircle, Info } from "lucide-react";
import { toast } from "sonner";
import { RiskMatrix, RiskRatingPill, ControlEffectivenessBadge } from "@/components/cg/shared";

export const Route = createFileRoute("/risk")({
  ssr: false,
  validateSearch: (s: Record<string, unknown>) => ({ r: typeof s.r === "string" ? s.r : undefined }),
  head: () => ({
    meta: [
      { title: "Risk - Jojan One" },
      { name: "description", content: "Business risk register, matrix and mitigation tracker." },
    ],
  }),
  component: RiskPage,
});

const CATEGORIES: RiskCategory[] = ["compliance","contracts","data_protection","cyber","people","financial","operational","supplier","strategic"];

function RiskPage() {
  const s = useCoreData((x) => x);
  const nav = useNavigate();
  const { r: openR } = Route.useSearch();
  const m = riskMetrics(s);
  const [tab, setTab] = useState("register");
  const [matrixView, setMatrixView] = useState<"inherent" | "residual">("residual");
  const [q, setQ] = useState("");
  const [catF, setCatF] = useState<string>("all");
  const [statusF, setStatusF] = useState<string>("open");
  const [showCalc, setShowCalc] = useState(false);
  const [detailId, setDetailId] = useState<string | null>(openR ?? null);
  const [form, setForm] = useState<Risk | null>(null);
  const [acceptId, setAcceptId] = useState<string | null>(null);
  const [closeId, setCloseId] = useState<string | null>(null);
  const [reason, setReason] = useState("");
  const [newMitFor, setNewMitFor] = useState<string | null>(null);
  const [newMitLabel, setNewMitLabel] = useState("");
  const [newMitDue, setNewMitDue] = useState("");

  const filtered = useMemo(() => s.risks
    .filter((r) => (statusF === "all" ? true : r.status === statusF))
    .filter((r) => (catF === "all" ? true : r.risk_category === catF))
    .filter((r) => (q ? r.risk_title.toLowerCase().includes(q.toLowerCase()) : true))
    .sort((a, b) => b.residual_score - a.residual_score),
    [s.risks, statusF, catF, q]);
  const detail = s.risks.find((r) => r.id === detailId) ?? null;

  const askJovaAbout = (r: Risk) => {
    const cid = createConversation(`Risk: ${r.risk_title}`);
    appendMessage({ conversation_id: cid, sender: "user", content: `Explain the risk "${r.risk_title}"`, reference_type: "risk", reference_id: r.id, suggested_action: null });
    nav({ to: "/jova", search: { c: cid } });
  };
  const printRisk = (r: Risk) => {
    const w = window.open("", "_blank"); if (!w) return;
    w.document.write(`<html><head><title>${r.risk_title}</title><style>body{font-family:system-ui;padding:2rem;max-width:720px}</style></head><body>
      <h1>${r.risk_title}</h1><p>${r.risk_category} • ${r.inherent_rating} inherent • ${r.residual_rating} residual</p>
      <p><strong>Description:</strong> ${r.description}</p>
      <p><strong>Cause:</strong> ${r.cause}</p>
      <p><strong>Consequence:</strong> ${r.consequence}</p>
      <p><strong>Controls:</strong> ${r.controls}</p>
      <p><strong>Response:</strong> ${r.response}</p>
      <p><strong>Mitigations:</strong></p><ul>${r.mitigation_actions.map((m) => `<li>${m.label} - ${m.status}${m.due_date ? " (due " + m.due_date.slice(0,10) + ")" : ""}</li>`).join("")}</ul>
      <p style="font-size:11px;color:#666;margin-top:2rem">Generated by Jojan One.</p></body></html>`); w.print();
  };

  return (
    <div className="mx-auto flex max-w-6xl flex-col gap-6 p-6">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h1 className="flex items-center gap-2 text-[22px] font-semibold text-foreground"><AlertTriangle className="h-5 w-5" strokeWidth={1.75} /> Risk</h1>
          <p className="mt-1 text-[13px] text-muted-foreground">Business risk register and 5×5 matrix. Transparent, deterministic scoring.</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => setShowCalc(true)}><HelpCircle className="mr-1 h-4 w-4" />How is this calculated?</Button>
          <Button onClick={() => setForm(newRiskDraft())}><Plus className="mr-1 h-4 w-4" />New risk</Button>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-3 md:grid-cols-4">
        <MetricCard label="Open risks" value={m.open.length} />
        <MetricCard label="High inherent" value={m.highInherent.length} tone={m.highInherent.length ? "warning" : "default"} />
        <MetricCard label="High residual" value={m.highResidual.length} tone={m.highResidual.length ? "danger" : "success"} />
        <MetricCard label="Reviews overdue" value={m.overdueReview.length} tone={m.overdueReview.length ? "warning" : "default"} />
        <MetricCard label="Mitigations overdue" value={m.overdueMit.length} tone={m.overdueMit.length ? "warning" : "default"} />
        <MetricCard label="Accepted" value={m.accepted.length} />
        <MetricCard label="Closed this month" value={m.closedMonth.length} tone="success" />
      </div>

      <Tabs value={tab} onValueChange={setTab}>
        <TabsList><TabsTrigger value="register">Register</TabsTrigger><TabsTrigger value="matrix">Matrix</TabsTrigger></TabsList>
      </Tabs>

      {tab === "register" && (
        <>
          <div className="flex flex-wrap gap-2 rounded-lg border border-border bg-card p-3">
            <Input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search risks…" className="flex-1 min-w-[200px]" />
            <Select value={catF} onValueChange={setCatF}><SelectTrigger className="w-[180px]"><SelectValue placeholder="Category" /></SelectTrigger>
              <SelectContent><SelectItem value="all">All categories</SelectItem>{CATEGORIES.map((c) => <SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select>
            <Select value={statusF} onValueChange={setStatusF}><SelectTrigger className="w-[140px]"><SelectValue placeholder="Status" /></SelectTrigger>
              <SelectContent><SelectItem value="all">All</SelectItem><SelectItem value="open">Open</SelectItem><SelectItem value="accepted">Accepted</SelectItem><SelectItem value="closed">Closed</SelectItem></SelectContent></Select>
          </div>

          {filtered.length === 0 ? <EmptyState icon={AlertTriangle} title="No risks match" /> : (
            <div className="overflow-hidden rounded-lg border border-border bg-card">
              <table className="w-full text-[13px]">
                <thead className="bg-[oklch(0.98_0.003_260)] text-[11px] uppercase tracking-wider text-muted-foreground"><tr><th className="p-3 text-left">Risk</th><th className="p-3 text-left">Category</th><th className="p-3 text-left">Inherent</th><th className="p-3 text-left">Residual</th><th className="p-3 text-left">Owner</th><th className="p-3 text-left">Review</th><th className="p-3" /></tr></thead>
                <tbody>
                  {filtered.map((r) => (
                    <tr key={r.id} className="border-t border-border hover:bg-accent/40">
                      <td className="p-3"><button className="font-medium hover:underline" onClick={() => setDetailId(r.id)}>{r.risk_title}</button></td>
                      <td className="p-3">{r.risk_category}</td>
                      <td className="p-3"><RiskRatingPill rating={r.inherent_rating} /> <span className="ml-1 text-[11px] text-muted-foreground">{r.inherent_score}</span></td>
                      <td className="p-3"><RiskRatingPill rating={r.residual_rating} /> <span className="ml-1 text-[11px] text-muted-foreground">{r.residual_score}</span></td>
                      <td className="p-3">{r.risk_owner}</td>
                      <td className="p-3">{r.review_date ? formatDate(r.review_date) : "-"}</td>
                      <td className="p-3 text-right"><Button size="sm" variant="ghost" onClick={() => setDetailId(r.id)}>Open</Button></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </>
      )}

      {tab === "matrix" && (
        <Card className="border border-border bg-card p-5 shadow-none">
          <div className="mb-3 flex items-center justify-between">
            <SectionHeader title="Risk matrix" description="5×5 likelihood × impact." />
            <div className="flex gap-2"><Button size="sm" variant={matrixView === "inherent" ? "default" : "outline"} onClick={() => setMatrixView("inherent")}>Inherent</Button><Button size="sm" variant={matrixView === "residual" ? "default" : "outline"} onClick={() => setMatrixView("residual")}>Residual</Button></div>
          </div>
          <RiskMatrix risks={s.risks.filter((r) => r.status === "open" || r.status === "accepted")} view={matrixView} onSelect={(r) => setDetailId(r.id)} />
        </Card>
      )}

      <DetailDrawer open={!!detail} onOpenChange={(v) => !v && setDetailId(null)} title={detail?.risk_title ?? ""} description={detail ? `${detail.risk_category} • ${detail.response}` : ""}>
        {detail && (
          <div className="flex flex-col gap-3 text-[13px]">
            <div className="flex flex-wrap gap-2">
              <RiskRatingPill rating={detail.inherent_rating} />
              <RiskRatingPill rating={detail.residual_rating} />
              <ControlEffectivenessBadge level={detail.control_effectiveness} />
            </div>
            <p><strong>Description:</strong> {detail.description}</p>
            <p><strong>Cause:</strong> {detail.cause}</p>
            <p><strong>Consequence:</strong> {detail.consequence}</p>
            <div className="grid grid-cols-2 gap-3 rounded border border-border p-2 text-[12px]">
              <div>Inherent likelihood: <strong>{detail.likelihood}</strong></div>
              <div>Inherent impact: <strong>{detail.impact}</strong></div>
              <div>Inherent score: <strong>{detail.inherent_score}</strong></div>
              <div>Residual likelihood: <strong>{detail.residual_likelihood}</strong></div>
              <div>Residual impact: <strong>{detail.residual_impact}</strong></div>
              <div>Residual score: <strong>{detail.residual_score}</strong></div>
            </div>
            <p><strong>Controls:</strong> {detail.controls || "-"}</p>
            <div>
              <div className="flex items-center justify-between"><p className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">Mitigations</p><Button size="sm" variant="ghost" onClick={() => { setNewMitFor(detail.id); setNewMitLabel(""); setNewMitDue(""); }}><Plus className="mr-1 h-3.5 w-3.5" />Add</Button></div>
              <ul className="mt-1 space-y-1">
                {detail.mitigation_actions.length === 0 && <li className="text-muted-foreground">None recorded.</li>}
                {detail.mitigation_actions.map((m) => (
                  <li key={m.id} className="flex items-center justify-between rounded border border-border p-2">
                    <span><strong>{m.label}</strong>{m.due_date ? <span className="ml-1 text-[11px] text-muted-foreground">due {m.due_date.slice(0,10)}</span> : null}</span>
                    {m.status === "open" ? <Button size="sm" variant="outline" onClick={() => completeMitigation(detail.id, m.id)}><Check className="mr-1 h-3.5 w-3.5" />Complete</Button> : <span className="text-[11px] text-muted-foreground">✓ done</span>}
                  </li>
                ))}
              </ul>
            </div>
            {(detail.linked_contract_id || detail.linked_obligation_id || detail.linked_processing_activity_id || detail.linked_entity_id) && (
              <div className="rounded border border-border p-2">
                <p className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">Linked records</p>
                <div className="mt-1 flex flex-wrap gap-2">
                  {detail.linked_contract_id && <Button size="sm" variant="ghost" onClick={() => nav({ to: "/contracts", search: { c: detail.linked_contract_id! } })}>Contract</Button>}
                  {detail.linked_obligation_id && <Button size="sm" variant="ghost" onClick={() => nav({ to: "/compliance", search: { o: detail.linked_obligation_id! } })}>Obligation</Button>}
                  {detail.linked_processing_activity_id && <Button size="sm" variant="ghost" onClick={() => nav({ to: "/gdpr", search: { pa: detail.linked_processing_activity_id! } })}>Processing activity</Button>}
                  {detail.linked_entity_id && <Button size="sm" variant="ghost" onClick={() => nav({ to: "/business-map", search: { e: detail.linked_entity_id! } })}>Business Map</Button>}
                </div>
              </div>
            )}
            <div className="flex flex-wrap gap-2 border-t border-border pt-3">
              <Button size="sm" onClick={() => setForm(detail)}>Edit</Button>
              {detail.status === "open" && <Button size="sm" variant="outline" onClick={() => { setAcceptId(detail.id); setReason(""); }}>Accept</Button>}
              {detail.status === "open" && <Button size="sm" variant="outline" onClick={() => { setCloseId(detail.id); setReason(""); }}>Close</Button>}
              {detail.status !== "open" && <Button size="sm" variant="outline" onClick={() => { reopenRisk(detail.id); toast.success("Reopened."); }}><RotateCcw className="mr-1 h-3.5 w-3.5" />Reopen</Button>}
              <Button size="sm" variant="ghost" onClick={() => askJovaAbout(detail)}><MessageSquare className="mr-1 h-3.5 w-3.5" />Ask Jova</Button>
              <Button size="sm" variant="ghost" onClick={() => printRisk(detail)}><Printer className="mr-1 h-3.5 w-3.5" />Print</Button>
              <Button size="sm" variant="ghost" onClick={() => { if (confirm("Delete risk?")) { deleteRisk(detail.id); toast.success("Deleted."); setDetailId(null); } }}>Delete</Button>
            </div>
          </div>
        )}
      </DetailDrawer>

      {/* Edit dialog */}
      <Dialog open={!!form} onOpenChange={(v) => !v && setForm(null)}>
        <DialogContent className="max-w-lg">
          <DialogHeader><DialogTitle>{s.risks.find((r) => r.id === form?.id) ? "Edit risk" : "New risk"}</DialogTitle></DialogHeader>
          {form && (
            <div className="grid gap-3">
              <Field label="Title" required><Input value={form.risk_title} onChange={(e) => setForm({ ...form, risk_title: e.target.value })} /></Field>
              <div className="grid grid-cols-2 gap-3">
                <Field label="Category">
                  <Select value={form.risk_category} onValueChange={(v) => setForm({ ...form, risk_category: v as RiskCategory })}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>{CATEGORIES.map((c) => <SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent>
                  </Select>
                </Field>
                <Field label="Owner"><Input value={form.risk_owner} onChange={(e) => setForm({ ...form, risk_owner: e.target.value })} /></Field>
                <Field label="Response">
                  <Select value={form.response} onValueChange={(v) => setForm({ ...form, response: v as RiskResponse })}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>{["avoid","reduce","transfer","accept","monitor"].map((r) => <SelectItem key={r} value={r}>{r}</SelectItem>)}</SelectContent>
                  </Select>
                </Field>
                <Field label="Control effectiveness">
                  <Select value={form.control_effectiveness} onValueChange={(v) => setForm({ ...form, control_effectiveness: v as Risk["control_effectiveness"] })}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>{["strong","adequate","weak","none"].map((r) => <SelectItem key={r} value={r}>{r}</SelectItem>)}</SelectContent>
                  </Select>
                </Field>
              </div>
              <Field label="Description"><Textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} rows={2} /></Field>
              <div className="grid grid-cols-2 gap-3">
                <Field label="Cause"><Textarea value={form.cause} onChange={(e) => setForm({ ...form, cause: e.target.value })} rows={2} /></Field>
                <Field label="Consequence"><Textarea value={form.consequence} onChange={(e) => setForm({ ...form, consequence: e.target.value })} rows={2} /></Field>
              </div>
              <Field label="Controls"><Textarea value={form.controls} onChange={(e) => setForm({ ...form, controls: e.target.value })} rows={2} /></Field>
              <div className="grid grid-cols-4 gap-3">
                <Field label="Inh. Likel."><Input type="number" min={1} max={5} value={form.likelihood} onChange={(e) => setForm({ ...form, likelihood: clamp(Number(e.target.value)) })} /></Field>
                <Field label="Inh. Impact"><Input type="number" min={1} max={5} value={form.impact} onChange={(e) => setForm({ ...form, impact: clamp(Number(e.target.value)) })} /></Field>
                <Field label="Res. Likel."><Input type="number" min={1} max={5} value={form.residual_likelihood} onChange={(e) => setForm({ ...form, residual_likelihood: clamp(Number(e.target.value)) })} /></Field>
                <Field label="Res. Impact"><Input type="number" min={1} max={5} value={form.residual_impact} onChange={(e) => setForm({ ...form, residual_impact: clamp(Number(e.target.value)) })} /></Field>
              </div>
              <Field label="Review date"><Input type="date" value={form.review_date?.slice(0,10) ?? ""} onChange={(e) => setForm({ ...form, review_date: e.target.value ? new Date(e.target.value).toISOString() : null })} /></Field>
            </div>
          )}
          <DialogFooter>
            <Button variant="ghost" onClick={() => setForm(null)}>Cancel</Button>
            <Button onClick={() => { if (!form?.risk_title) return toast.error("Title required."); upsertRisk(form); toast.success("Saved."); setForm(null); }}>Save</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Accept / Close */}
      <Dialog open={!!acceptId || !!closeId} onOpenChange={(v) => { if (!v) { setAcceptId(null); setCloseId(null); } }}>
        <DialogContent>
          <DialogHeader><DialogTitle>{acceptId ? "Accept risk" : "Close risk"}</DialogTitle></DialogHeader>
          <Textarea value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Reason required…" />
          <DialogFooter>
            <Button variant="ghost" onClick={() => { setAcceptId(null); setCloseId(null); }}>Cancel</Button>
            <Button onClick={() => { if (!reason.trim()) return toast.error("Reason required."); if (acceptId) { acceptRisk(acceptId, reason.trim()); toast.success("Accepted."); } else if (closeId) { closeRisk(closeId, reason.trim()); toast.success("Closed."); } setAcceptId(null); setCloseId(null); }}>Save</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Add mitigation */}
      <Dialog open={!!newMitFor} onOpenChange={(v) => !v && setNewMitFor(null)}>
        <DialogContent>
          <DialogHeader><DialogTitle>Add mitigation</DialogTitle></DialogHeader>
          <div className="grid gap-3">
            <Field label="Description" required><Input value={newMitLabel} onChange={(e) => setNewMitLabel(e.target.value)} /></Field>
            <Field label="Due date"><Input type="date" value={newMitDue} onChange={(e) => setNewMitDue(e.target.value)} /></Field>
          </div>
          <DialogFooter>
            <Button variant="ghost" onClick={() => setNewMitFor(null)}>Cancel</Button>
            <Button onClick={() => { if (!newMitLabel.trim() || !newMitFor) return toast.error("Description required."); addMitigation(newMitFor, newMitLabel.trim(), newMitDue ? new Date(newMitDue).toISOString() : null); toast.success("Added."); setNewMitFor(null); }}>Add</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Calc explainer */}
      <Dialog open={showCalc} onOpenChange={setShowCalc}>
        <DialogContent>
          <DialogHeader><DialogTitle>How risk scores are calculated</DialogTitle></DialogHeader>
          <div className="text-[13px] space-y-2">
            <p>Each risk is scored on a 5×5 matrix.</p>
            <p><strong>Likelihood × Impact = Score</strong></p>
            <ul className="list-disc pl-5">
              <li>1–4: Low</li><li>5–9: Medium</li><li>10–16: High</li><li>17–25: Critical</li>
            </ul>
            <p>Inherent score reflects the risk before controls. Residual score reflects the risk after existing controls are applied.</p>
          </div>
        </DialogContent>
      </Dialog>

      <p className="text-[11px] text-muted-foreground"><Info className="mr-1 inline h-3.5 w-3.5" />Ratings are your assessment. Jojan One does not perform live risk monitoring.</p>
    </div>
  );
}

function clamp(n: number): number {
  if (Number.isNaN(n)) return 1;
  return Math.max(1, Math.min(5, Math.round(n)));
}