import { and, desc, eq, sql } from "drizzle-orm";
import { withUser, type UserClaims } from "../db";
import { notifications } from "../db/schema";

// In-app notifications feed (member-facing). All reads/writes run through
// withUser() (RLS). Rows are generated by the reminder engine; here members
// read them, mark them read, and follow the deep-link to the source module.

// Map a notification's source module to the route that resolves it.
const HREF: Record<string, string> = {
  compliance: "/compliance",
  contracts: "/contracts",
  risk: "/risk",
  gdpr: "/gdpr",
  hr: "/hr",
  governance: "/governance",
  "tender-ready": "/tender-ready",
  "investor-ready": "/investor-ready",
  academy: "/academy",
};

export interface NotificationRow {
  id: string;
  kind: string;
  title: string;
  description: string | null;
  href: string;
  read: boolean;
  createdAt: Date;
}

export function listNotifications(
  claims: UserClaims,
  limit = 30,
): Promise<NotificationRow[]> {
  return withUser(claims, async (tx) => {
    const rows = await tx
      .select()
      .from(notifications)
      .orderBy(desc(notifications.createdAt))
      .limit(limit);
    return rows.map((r) => ({
      id: r.id,
      kind: r.kind,
      title: r.title,
      description: r.description,
      href: HREF[r.referenceType ?? ""] ?? "/dashboard",
      read: r.read,
      createdAt: r.createdAt,
    }));
  });
}

export function unreadCount(claims: UserClaims): Promise<number> {
  return withUser(claims, async (tx) => {
    const rows = await tx
      .select({ n: sql<number>`count(*)` })
      .from(notifications)
      .where(eq(notifications.read, false));
    return Number(rows[0]?.n ?? 0);
  });
}

export function markRead(claims: UserClaims, id: string) {
  return withUser(claims, async (tx) => {
    const rows = await tx
      .update(notifications)
      .set({ read: true })
      .where(and(eq(notifications.id, id)))
      .returning({ id: notifications.id });
    return rows.length > 0;
  });
}

export function markAllRead(claims: UserClaims) {
  return withUser(claims, async (tx) => {
    const rows = await tx
      .update(notifications)
      .set({ read: true })
      .where(eq(notifications.read, false))
      .returning({ id: notifications.id });
    return rows.length;
  });
}
