// =============================================================================
// Conditional onboarding schema - the single source of truth.
//
// Order of sections is the wizard order. Only "initial" fields gate first-time
// completion; everything else is progressive (collected later in-module) or
// optional. See types.ts for the meaning of each attribute and logic.ts for the
// visibility / gate / persistence helpers that consume this data.
// =============================================================================
import type { OnboardingSchema, Option, Role } from "./types";

// --- Reusable option sets ----------------------------------------------------
const BUSINESS_STRUCTURES: Option[] = [
  { value: "limited_company", label: "Private limited company (Ltd)" },
  { value: "llp", label: "Limited liability partnership (LLP)" },
  { value: "partnership", label: "Partnership" },
  { value: "sole_trader", label: "Sole trader" },
  { value: "charity", label: "Charity / CIC" },
  { value: "other", label: "Other" },
];

const COMPANY_STATUSES: Option[] = [
  { value: "active", label: "Active / trading" },
  { value: "in_setup", label: "Setting up / pre-trading" },
  { value: "dormant", label: "Dormant" },
  { value: "ceased", label: "Ceased trading" },
];

const COUNTRIES: Option[] = [
  { value: "united_kingdom", label: "United Kingdom" },
  { value: "ireland", label: "Ireland" },
  { value: "other", label: "Other" },
];

const OPERATING_COUNTRIES: Option[] = [
  { value: "uk", label: "United Kingdom" },
  { value: "eu", label: "European Union" },
  { value: "us", label: "United States" },
  { value: "rest_of_world", label: "Rest of world" },
];

const EMPLOYEE_RANGES: Option[] = [
  { value: "0", label: "None" },
  { value: "1-4", label: "1–4" },
  { value: "5-9", label: "5–9" },
  { value: "10-24", label: "10–24" },
  { value: "25-49", label: "25–49" },
  { value: "50-99", label: "50–99" },
  { value: "100-249", label: "100–249" },
  { value: "250+", label: "250+" },
];

const CONTRACTOR_RANGES: Option[] = [
  { value: "0", label: "None" },
  { value: "1-4", label: "1–4" },
  { value: "5-9", label: "5–9" },
  { value: "10-24", label: "10–24" },
  { value: "25+", label: "25+" },
];

const REVENUE_BANDS: Option[] = [
  { value: "under_50k", label: "Under £50k" },
  { value: "50k_90k", label: "£50k–£89,999" },
  { value: "90k_250k", label: "£90k–£249,999" },
  { value: "250k_500k", label: "£250k–£499,999" },
  { value: "500k_1m", label: "£500k–£999,999" },
  { value: "1m_5m", label: "£1m–£4.99m" },
  { value: "5m_plus", label: "£5m+" },
];

const SECTORS: Option[] = [
  { value: "professional_services", label: "Professional services" },
  { value: "technology", label: "Technology / software" },
  { value: "retail", label: "Retail / e-commerce" },
  { value: "hospitality", label: "Hospitality / food" },
  { value: "construction", label: "Construction / trades" },
  { value: "healthcare", label: "Health / care" },
  { value: "education", label: "Education / training" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "finance", label: "Finance / insurance" },
  { value: "creative_media", label: "Creative / media" },
  { value: "transport_logistics", label: "Transport / logistics" },
  { value: "property", label: "Property / real estate" },
  { value: "charity_nonprofit", label: "Charity / non-profit" },
  { value: "other", label: "Other" },
];

const SELLS: Option[] = [
  { value: "products", label: "Products" },
  { value: "services", label: "Services" },
  { value: "both", label: "Both" },
];

const DATA_SUBJECTS: Option[] = [
  { value: "employees", label: "Employees / workers" },
  { value: "customers", label: "Customers" },
  { value: "suppliers", label: "Suppliers / contractors" },
  { value: "website_visitors", label: "Website visitors" },
  { value: "job_applicants", label: "Job applicants" },
  { value: "members", label: "Members / donors" },
  { value: "patients_clients", label: "Patients / clients" },
  { value: "children", label: "Children" },
  { value: "other", label: "Other" },
];

const DATA_CATEGORIES: Option[] = [
  { value: "contact_details", label: "Contact details" },
  { value: "identity", label: "Identity documents" },
  { value: "financial", label: "Financial / payment" },
  { value: "employment", label: "Employment records" },
  { value: "online_identifiers", label: "Online identifiers / cookies" },
  { value: "marketing", label: "Marketing preferences" },
  { value: "other", label: "Other" },
];

const PROCESSING_PURPOSES: Option[] = [
  { value: "service_delivery", label: "Delivering products / services" },
  { value: "employment", label: "Employing / managing staff" },
  { value: "payments", label: "Taking payments" },
  { value: "marketing", label: "Marketing" },
  { value: "legal_compliance", label: "Legal / regulatory compliance" },
  { value: "analytics", label: "Analytics / improvement" },
  { value: "other", label: "Other" },
];

const CONTRACT_TYPES: Option[] = [
  { value: "customer", label: "Customer / sales" },
  { value: "supplier", label: "Supplier / purchase" },
  { value: "employment", label: "Employment" },
  { value: "contractor", label: "Contractor / freelance" },
  { value: "software", label: "Software / SaaS" },
  { value: "lease", label: "Property / lease" },
  { value: "nda", label: "NDA" },
  { value: "other", label: "Other" },
];

const GROWTH_OBJECTIVES: Option[] = [
  { value: "organisation", label: "General business organisation" },
  { value: "compliance", label: "Compliance readiness" },
  { value: "gdpr", label: "GDPR readiness" },
  { value: "governance", label: "Governance improvement" },
  { value: "risk", label: "Risk management" },
  { value: "contracts", label: "Contract & renewal management" },
  { value: "hr", label: "HR management" },
  { value: "investor_ready", label: "Investor readiness" },
  { value: "tender_ready", label: "Tender readiness" },
  { value: "training", label: "Staff training" },
  { value: "reporting", label: "Reporting for lenders / insurers / advisers" },
];

const FUNDING_STAGES: Option[] = [
  { value: "not_raising", label: "Not currently raising" },
  { value: "pre_seed", label: "Pre-seed" },
  { value: "seed", label: "Seed" },
  { value: "series_a_plus", label: "Series A+" },
  { value: "debt_grant", label: "Debt / grant" },
];

const COMMS_STYLES: Option[] = [
  { value: "friendly", label: "Friendly & encouraging" },
  { value: "neutral", label: "Neutral & concise" },
  { value: "formal", label: "Formal & precise" },
];

const EXPLANATION_DEPTH: Option[] = [
  { value: "plain_english", label: "Plain English" },
  { value: "detailed", label: "Detailed" },
];

const SUPPORT_TYPES: Option[] = [
  { value: "solicitor", label: "Solicitor" },
  { value: "accountant", label: "Accountant" },
  { value: "hr_adviser", label: "HR adviser" },
  { value: "data_protection", label: "Data-protection specialist" },
  { value: "health_safety", label: "Health & safety consultant" },
  { value: "insurance_broker", label: "Insurance broker" },
];

const BRIEFING_TOPICS: Option[] = [
  { value: "compliance", label: "Compliance deadlines" },
  { value: "contracts", label: "Contract renewals" },
  { value: "hr", label: "HR & people" },
  { value: "gdpr", label: "Data protection" },
  { value: "risk", label: "Risk & insurance" },
  { value: "governance", label: "Governance" },
];

const EVIDENCE_KINDS: Option[] = [
  { value: "incorporation", label: "Incorporation documents" },
  { value: "org_chart", label: "Organisation / ownership chart" },
  { value: "policies", label: "Policies" },
  { value: "insurance", label: "Insurance certificates" },
  { value: "contracts", label: "Contracts" },
  { value: "handbook", label: "Employee handbook" },
  { value: "accounts", label: "Statutory accounts" },
  { value: "risk_register", label: "Risk register" },
  { value: "governance", label: "Governance records" },
  { value: "gdpr", label: "GDPR records" },
  { value: "compliance_calendar", label: "Compliance calendar" },
];

const PLANS: Option[] = [
  { value: "starter", label: "Starter (1 seat)" },
  { value: "growth", label: "Growth (5 seats)" },
];

const OWNER: Role[] = ["owner_admin"];
const OWNER_MANAGER: Role[] = ["owner_admin", "manager"];

// Yes / No / Unsure applicability questions (section 6) share these settings.
const applicability = (
  id: string,
  label: string,
  destinationModule: Parameters<
    typeof mk
  >[0]["destinationModule"] = "compliance",
) =>
  mk({
    id,
    label,
    type: "yesno_unsure",
    required: "progressive",
    sensitivity: "standard",
    permissions: OWNER,
    destinationModule,
  });

// Small helper so every field object is complete and consistently shaped.
function mk(f: OnboardingSchema[number]["fields"][number]) {
  return f;
}

export const ONBOARDING_SCHEMA: OnboardingSchema = [
  // 1 - Account owner --------------------------------------------------------
  {
    id: "owner",
    title: "Account owner",
    summary:
      "Who is setting up this account. Some details come from your login.",
    fields: [
      mk({
        id: "owner.full_name",
        label: "Full name",
        type: "text",
        required: "initial",
        validation: { minLength: 2, maxLength: 200 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "auth",
      }),
      mk({
        id: "owner.job_title",
        label: "Job title / role",
        type: "text",
        required: "progressive",
        validation: { maxLength: 200 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "auth",
      }),
      mk({
        id: "owner.work_email",
        label: "Work email",
        type: "email",
        required: "initial",
        validation: { email: true, maxLength: 320 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "auth",
      }),
      mk({
        id: "owner.telephone",
        label: "Telephone number",
        type: "tel",
        required: "optional",
        validation: { maxLength: 40 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "auth",
      }),
      mk({
        id: "owner.password",
        label: "Password",
        help: "Set at sign-up and managed by our authentication provider. Never stored by Jojan One.",
        type: "password",
        required: "initial",
        sensitivity: "secret",
        permissions: OWNER,
        destinationModule: "auth",
        neverStore: true,
      }),
      mk({
        id: "owner.authorised",
        label: "I am authorised to create this company account",
        type: "consent",
        required: "initial",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "auth",
      }),
      mk({
        id: "owner.accept_terms",
        label:
          "I accept the Terms of Service, Privacy Notice and data-processing terms",
        type: "consent",
        required: "initial",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "auth",
      }),
      mk({
        id: "owner.marketing_consent",
        label: "Send me product updates and tips (optional)",
        type: "boolean",
        required: "optional",
        sensitivity: "low",
        permissions: OWNER,
        destinationModule: "auth",
      }),
    ],
  },

  // 2 - Company identity -----------------------------------------------------
  {
    id: "company",
    title: "Company identity",
    summary: "The basics that identify your business.",
    fields: [
      mk({
        id: "company.legal_name",
        label: "Legal company name",
        type: "text",
        required: "initial",
        validation: { minLength: 2, maxLength: 200 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "profile",
      }),
      mk({
        id: "company.trading_name",
        label: "Trading name",
        help: "If different from the legal name.",
        type: "text",
        required: "optional",
        validation: { maxLength: 200 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "profile",
      }),
      mk({
        id: "company.business_structure",
        label: "Business structure",
        type: "select",
        options: BUSINESS_STRUCTURES,
        required: "initial",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "profile",
      }),
      mk({
        id: "company.company_number",
        label: "Company number",
        help: "Required for registered companies and LLPs.",
        type: "text",
        required: "optional",
        requiredIf: {
          field: "company.business_structure",
          in: ["limited_company", "llp"],
        },
        showIf: {
          field: "company.business_structure",
          in: ["limited_company", "llp", "charity"],
        },
        validation: { maxLength: 20 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "profile",
      }),
      mk({
        id: "company.status",
        label: "Company status",
        type: "select",
        options: COMPANY_STATUSES,
        required: "progressive",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "profile",
      }),
      mk({
        id: "company.incorporation_date",
        label: "Incorporation or trading-start date",
        type: "date",
        required: "progressive",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "profile",
      }),
      mk({
        id: "company.registered_country",
        label: "Registered country",
        type: "select",
        options: COUNTRIES,
        required: "initial",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "profile",
      }),
      mk({
        id: "company.registered_address",
        label: "Registered office address",
        type: "address",
        required: "progressive",
        validation: { maxLength: 500 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "profile",
      }),
      mk({
        id: "company.primary_address",
        label: "Primary business address",
        help: "If different from the registered office.",
        type: "address",
        required: "optional",
        validation: { maxLength: 500 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "profile",
      }),
      mk({
        id: "company.website",
        label: "Website",
        type: "url",
        required: "optional",
        validation: { url: true, maxLength: 300 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "profile",
      }),
      mk({
        id: "company.business_email",
        label: "Main business email",
        type: "email",
        required: "progressive",
        validation: { email: true, maxLength: 320 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "profile",
      }),
      mk({
        id: "company.telephone",
        label: "Main telephone number",
        type: "tel",
        required: "optional",
        validation: { maxLength: 40 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "profile",
      }),
      mk({
        id: "company.industry",
        label: "Industry / sector",
        type: "select",
        options: SECTORS,
        required: "initial",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "profile",
      }),
      mk({
        id: "company.description",
        label: "Short business description",
        type: "textarea",
        required: "progressive",
        validation: { maxLength: 600 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "profile",
      }),
      mk({
        id: "company.logo",
        label: "Company logo (optional)",
        type: "file",
        required: "optional",
        sensitivity: "low",
        permissions: OWNER,
        destinationModule: "settings",
      }),
      mk({
        id: "company.brand_color",
        label: "Preferred brand colour (optional)",
        type: "color",
        required: "optional",
        sensitivity: "low",
        permissions: OWNER,
        destinationModule: "settings",
      }),
    ],
  },

  // 3 - Business operations --------------------------------------------------
  {
    id: "ops",
    title: "Business operations",
    summary: "How your business runs day to day.",
    fields: [
      mk({
        id: "ops.employee_range",
        label: "Number of employees",
        type: "select",
        options: EMPLOYEE_RANGES,
        required: "initial",
        sensitivity: "standard",
        permissions: OWNER_MANAGER,
        destinationModule: "profile",
      }),
      mk({
        id: "ops.contractor_range",
        label: "Number of contractors",
        type: "select",
        options: CONTRACTOR_RANGES,
        required: "initial",
        sensitivity: "standard",
        permissions: OWNER_MANAGER,
        destinationModule: "profile",
      }),
      mk({
        id: "ops.revenue_band",
        label: "Turnover / revenue band",
        type: "select",
        options: REVENUE_BANDS,
        required: "progressive",
        sensitivity: "confidential",
        permissions: OWNER,
        destinationModule: "profile",
      }),
      mk({
        id: "ops.financial_year_end",
        label: "Financial year-end",
        help: "Day and month, e.g. 31 March.",
        type: "text",
        required: "progressive",
        validation: { maxLength: 20 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "profile",
      }),
      mk({
        id: "ops.vat_registered",
        label: "VAT registered?",
        type: "yesno_unsure",
        required: "progressive",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "compliance",
      }),
      mk({
        id: "ops.vat_number",
        label: "VAT number",
        type: "text",
        required: "optional",
        showIf: { field: "ops.vat_registered", equals: "yes" },
        validation: { maxLength: 20 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "compliance",
      }),
      mk({
        id: "ops.operating_countries",
        label: "Countries in which you operate",
        type: "multiselect",
        options: OPERATING_COUNTRIES,
        required: "progressive",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "profile",
      }),
      mk({
        id: "ops.trades_internationally",
        label: "Do you trade internationally?",
        type: "boolean",
        required: "progressive",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "compliance",
      }),
      mk({
        id: "ops.sells",
        label: "Do you sell products, services or both?",
        type: "select",
        options: SELLS,
        required: "progressive",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "profile",
      }),
      mk({
        id: "ops.has_website",
        label: "Do you operate a website or digital service?",
        type: "boolean",
        required: "initial",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "compliance",
      }),
      mk({
        id: "ops.regulated_activities",
        label: "Do you undertake regulated activities?",
        type: "yesno_unsure",
        required: "progressive",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "compliance",
      }),
      mk({
        id: "ops.depends_on_suppliers",
        label: "Do you depend on important external suppliers?",
        type: "boolean",
        required: "progressive",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "contracts",
      }),
      mk({
        id: "ops.processes_personal_data",
        label: "Do you process personal data?",
        help: "Names, contact details, or any information about identifiable people.",
        type: "yesno_unsure",
        required: "initial",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "gdpr",
      }),
      mk({
        id: "ops.employs_staff",
        label: "Do you employ staff?",
        type: "boolean",
        required: "initial",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "hr",
      }),
      mk({
        id: "ops.uses_contractors",
        label: "Do you use contractors or off-payroll workers?",
        type: "boolean",
        required: "initial",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "hr",
      }),
    ],
  },

  // 4 - Ownership & governance ----------------------------------------------
  {
    id: "governance",
    title: "Ownership & governance",
    summary:
      "Just enough to configure the platform - full records live in Business Map and Governance.",
    fields: [
      mk({
        id: "governance.owners",
        label: "Directors, partners or owners",
        help: "You can add full details later in Business Map / Governance.",
        type: "people_list",
        required: "progressive",
        sensitivity: "confidential",
        permissions: OWNER,
        destinationModule: "business-map",
      }),
      mk({
        id: "governance.pscs",
        label: "Persons with significant control",
        type: "people_list",
        required: "progressive",
        sensitivity: "confidential",
        permissions: OWNER,
        destinationModule: "governance",
      }),
      mk({
        id: "governance.group_structure",
        label: "Parent, subsidiary or group relationships?",
        type: "yesno_unsure",
        required: "optional",
        sensitivity: "confidential",
        permissions: OWNER,
        destinationModule: "business-map",
      }),
      mk({
        id: "governance.company_secretary",
        label: "Company secretary (if applicable)",
        type: "text",
        required: "optional",
        validation: { maxLength: 200 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "governance",
      }),
      mk({
        id: "governance.board_frequency",
        label: "Governance / board meeting frequency",
        type: "select",
        options: [
          { value: "none", label: "No formal meetings yet" },
          { value: "ad_hoc", label: "Ad hoc" },
          { value: "monthly", label: "Monthly" },
          { value: "quarterly", label: "Quarterly" },
          { value: "annually", label: "Annually" },
        ],
        required: "optional",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "governance",
      }),
      mk({
        id: "governance.has_policies",
        label: "Do you have existing policies and approval arrangements?",
        type: "yesno_unsure",
        required: "optional",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "policies",
      }),
    ],
  },

  // 5 - Workforce profile ----------------------------------------------------
  {
    id: "workforce",
    title: "Workforce profile",
    summary: "A quick picture of your people. Full records go in HR later.",
    fields: [
      mk({
        id: "workforce.employment_locations",
        label: "Where are your people based?",
        type: "text",
        required: "optional",
        showIf: { field: "ops.employs_staff", truthy: true },
        validation: { maxLength: 300 },
        sensitivity: "standard",
        permissions: OWNER_MANAGER,
        destinationModule: "hr",
      }),
      mk({
        id: "workforce.remote_hybrid",
        label: "Do you use remote or hybrid working?",
        type: "boolean",
        required: "optional",
        showIf: { field: "ops.employs_staff", truthy: true },
        sensitivity: "standard",
        permissions: OWNER_MANAGER,
        destinationModule: "hr",
      }),
      mk({
        id: "workforce.overseas_workers",
        label: "Do you engage overseas workers?",
        type: "yesno_unsure",
        required: "optional",
        showIf: { field: "ops.employs_staff", truthy: true },
        sensitivity: "standard",
        permissions: OWNER_MANAGER,
        destinationModule: "hr",
      }),
      mk({
        id: "workforce.hr_owner",
        label: "Who is responsible for HR?",
        type: "text",
        required: "progressive",
        showIf: { field: "ops.employs_staff", truthy: true },
        validation: { maxLength: 200 },
        sensitivity: "standard",
        permissions: OWNER_MANAGER,
        destinationModule: "hr",
      }),
      mk({
        id: "workforce.rtw_owner",
        label: "Who is responsible for right-to-work checks?",
        type: "text",
        required: "optional",
        showIf: { field: "ops.employs_staff", truthy: true },
        validation: { maxLength: 200 },
        sensitivity: "standard",
        permissions: OWNER_MANAGER,
        destinationModule: "hr",
      }),
      mk({
        id: "workforce.training_owner",
        label: "Who is responsible for training?",
        type: "text",
        required: "optional",
        showIf: { field: "ops.employs_staff", truthy: true },
        validation: { maxLength: 200 },
        sensitivity: "standard",
        permissions: OWNER_MANAGER,
        destinationModule: "academy",
      }),
      mk({
        id: "workforce.has_handbook",
        label: "Do you have an employee handbook?",
        type: "yesno_unsure",
        required: "optional",
        showIf: { field: "ops.employs_staff", truthy: true },
        sensitivity: "standard",
        permissions: OWNER_MANAGER,
        destinationModule: "hr",
      }),
    ],
  },

  // 6 - Compliance applicability --------------------------------------------
  {
    id: "compliance",
    title: "Compliance applicability",
    summary:
      "Quick yes / no / unsure. “Unsure” never blocks you - it creates a review to look at later.",
    fields: [
      applicability(
        "compliance.company_filings",
        "UK limited-company filing responsibilities?",
      ),
      applicability(
        "compliance.pensions",
        "Workplace pension responsibilities?",
      ),
      applicability(
        "compliance.health_safety",
        "Health & safety responsibilities?",
        "risk",
      ),
      applicability("compliance.insurance", "Insurance requirements?", "risk"),
      applicability(
        "compliance.sector_obligations",
        "Sector-specific obligations?",
      ),
    ],
  },

  // 7 - Data protection & GDPR ----------------------------------------------
  {
    id: "gdpr",
    title: "Data protection & GDPR",
    summary:
      "Organisational facts about how you handle personal data - do not upload personal data here.",
    fields: [
      mk({
        id: "gdpr.data_subjects",
        label: "Whose personal data do you hold?",
        type: "multiselect",
        options: DATA_SUBJECTS,
        required: "progressive",
        showIf: { field: "ops.processes_personal_data", in: ["yes", "unsure"] },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "gdpr",
      }),
      mk({
        id: "gdpr.data_categories",
        label: "Broad categories of personal data processed",
        type: "multiselect",
        options: DATA_CATEGORIES,
        required: "progressive",
        showIf: { field: "ops.processes_personal_data", in: ["yes", "unsure"] },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "gdpr",
      }),
      mk({
        id: "gdpr.special_category",
        label: "Do you use special-category or criminal-offence data?",
        help: "Health, biometric, ethnicity, beliefs, sexual orientation, or offence data.",
        type: "yesno_unsure",
        required: "progressive",
        showIf: { field: "ops.processes_personal_data", in: ["yes", "unsure"] },
        sensitivity: "special_category",
        permissions: OWNER,
        destinationModule: "gdpr",
      }),
      mk({
        id: "gdpr.purposes",
        label: "Primary processing purposes",
        type: "multiselect",
        options: PROCESSING_PURPOSES,
        required: "progressive",
        showIf: { field: "ops.processes_personal_data", in: ["yes", "unsure"] },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "gdpr",
      }),
      mk({
        id: "gdpr.shares_with_processors",
        label: "Do you share data with suppliers / processors?",
        type: "yesno_unsure",
        required: "optional",
        showIf: { field: "ops.processes_personal_data", in: ["yes", "unsure"] },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "gdpr",
      }),
      mk({
        id: "gdpr.transfers_outside_uk",
        label: "Do you transfer data outside the UK?",
        type: "yesno_unsure",
        required: "optional",
        showIf: { field: "ops.processes_personal_data", in: ["yes", "unsure"] },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "gdpr",
      }),
      mk({
        id: "gdpr.ico_fee",
        label: "Do you pay an ICO data-protection fee?",
        type: "yesno_unsure",
        required: "optional",
        showIf: { field: "ops.processes_personal_data", in: ["yes", "unsure"] },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "gdpr",
      }),
      mk({
        id: "gdpr.has_privacy_notice",
        label: "Do you have a privacy notice?",
        type: "yesno_unsure",
        required: "optional",
        showIf: { field: "ops.processes_personal_data", in: ["yes", "unsure"] },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "gdpr",
      }),
      mk({
        id: "gdpr.has_ropa",
        label: "Do you have a Record of Processing Activities?",
        type: "yesno_unsure",
        required: "optional",
        showIf: { field: "ops.processes_personal_data", in: ["yes", "unsure"] },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "gdpr",
      }),
      mk({
        id: "gdpr.tracks_requests",
        label: "Do you track data-subject requests?",
        type: "yesno_unsure",
        required: "optional",
        showIf: { field: "ops.processes_personal_data", in: ["yes", "unsure"] },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "gdpr",
      }),
      mk({
        id: "gdpr.has_breach_process",
        label: "Do you have a breach-response process?",
        type: "yesno_unsure",
        required: "optional",
        showIf: { field: "ops.processes_personal_data", in: ["yes", "unsure"] },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "gdpr",
      }),
      mk({
        id: "gdpr.dp_owner",
        label: "Who is responsible for data protection?",
        type: "text",
        required: "progressive",
        showIf: { field: "ops.processes_personal_data", in: ["yes", "unsure"] },
        validation: { maxLength: 200 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "gdpr",
      }),
    ],
  },

  // 8 - Contracts & suppliers ------------------------------------------------
  {
    id: "contracts",
    title: "Contracts & suppliers",
    summary: "A quick picture of your contractual relationships.",
    fields: [
      mk({
        id: "contracts.active_count",
        label: "Approximate number of active contracts",
        type: "select",
        options: [
          { value: "0", label: "None yet" },
          { value: "1-10", label: "1–10" },
          { value: "11-50", label: "11–50" },
          { value: "51-200", label: "51–200" },
          { value: "200+", label: "200+" },
        ],
        required: "progressive",
        sensitivity: "standard",
        permissions: OWNER_MANAGER,
        destinationModule: "contracts",
      }),
      mk({
        id: "contracts.main_types",
        label: "Main contract types",
        type: "multiselect",
        options: CONTRACT_TYPES,
        required: "progressive",
        sensitivity: "standard",
        permissions: OWNER_MANAGER,
        destinationModule: "contracts",
      }),
      mk({
        id: "contracts.tracks_renewals",
        label: "Do you track renewal and notice dates?",
        type: "yesno_unsure",
        required: "optional",
        sensitivity: "standard",
        permissions: OWNER_MANAGER,
        destinationModule: "contracts",
      }),
      mk({
        id: "contracts.key_dependencies",
        label: "Important supplier or customer dependencies",
        type: "textarea",
        required: "optional",
        validation: { maxLength: 500 },
        sensitivity: "confidential",
        permissions: OWNER_MANAGER,
        destinationModule: "contracts",
      }),
      mk({
        id: "contracts.owner",
        label: "Who is responsible for contracts?",
        type: "text",
        required: "optional",
        validation: { maxLength: 200 },
        sensitivity: "standard",
        permissions: OWNER_MANAGER,
        destinationModule: "contracts",
      }),
      mk({
        id: "contracts.upload",
        label: "Upload or import an existing contract register (optional)",
        type: "file",
        required: "optional",
        sensitivity: "confidential",
        permissions: OWNER_MANAGER,
        destinationModule: "contracts",
      }),
    ],
  },

  // 9 - Risk & insurance -----------------------------------------------------
  {
    id: "risk",
    title: "Risk & insurance",
    summary: "Where your main risks are and what cover you hold.",
    fields: [
      mk({
        id: "risk.owner",
        label: "Who is responsible for risk?",
        type: "text",
        required: "optional",
        validation: { maxLength: 200 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "risk",
      }),
      mk({
        id: "risk.main_risks",
        label: "Main business risks",
        type: "textarea",
        required: "optional",
        validation: { maxLength: 600 },
        sensitivity: "confidential",
        permissions: OWNER,
        destinationModule: "risk",
      }),
      mk({
        id: "risk.has_register",
        label: "Do you have a risk register?",
        type: "yesno_unsure",
        required: "optional",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "risk",
      }),
      mk({
        id: "risk.ins_professional_indemnity",
        label: "Professional indemnity insurance?",
        type: "yesno_unsure",
        required: "optional",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "risk",
      }),
      mk({
        id: "risk.ins_public_liability",
        label: "Public liability insurance?",
        type: "yesno_unsure",
        required: "optional",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "risk",
      }),
      mk({
        id: "risk.ins_employers_liability",
        label: "Employers’ liability insurance?",
        type: "yesno_unsure",
        required: "optional",
        showIf: { field: "ops.employs_staff", truthy: true },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "risk",
      }),
      mk({
        id: "risk.ins_cyber",
        label: "Cyber insurance?",
        type: "yesno_unsure",
        required: "optional",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "risk",
      }),
      mk({
        id: "risk.ins_other",
        label: "Other sector-specific insurance?",
        type: "text",
        required: "optional",
        validation: { maxLength: 300 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "risk",
      }),
      mk({
        id: "risk.continuity_plans",
        label: "Do you have business-continuity and incident-response plans?",
        type: "yesno_unsure",
        required: "optional",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "risk",
      }),
    ],
  },

  // 10 - Growth objectives ---------------------------------------------------
  {
    id: "growth",
    title: "Growth objectives",
    summary: "What you want Jojan One to help you achieve.",
    fields: [
      mk({
        id: "growth.priorities",
        label: "Which outcomes matter most?",
        type: "multiselect",
        options: GROWTH_OBJECTIVES,
        required: "initial",
        validation: { minLength: 1 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "reports",
      }),
      mk({
        id: "growth.immediate_priorities",
        label: "Immediate priorities",
        type: "textarea",
        required: "optional",
        validation: { maxLength: 500 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "reports",
      }),
      mk({
        id: "growth.target_date",
        label: "Target date (if any)",
        type: "date",
        required: "optional",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "reports",
      }),
      mk({
        id: "growth.funding_stage",
        label: "Funding stage",
        type: "select",
        options: FUNDING_STAGES,
        required: "optional",
        showIf: { field: "growth.priorities", contains: "investor_ready" },
        sensitivity: "confidential",
        permissions: OWNER,
        destinationModule: "investor-ready",
      }),
      mk({
        id: "growth.funding_amount",
        label: "Amount sought",
        type: "text",
        required: "optional",
        showIf: { field: "growth.priorities", contains: "investor_ready" },
        validation: { maxLength: 40 },
        sensitivity: "confidential",
        permissions: OWNER,
        destinationModule: "investor-ready",
      }),
      mk({
        id: "growth.tender_activity",
        label: "Current tender activity",
        type: "textarea",
        required: "optional",
        showIf: { field: "growth.priorities", contains: "tender_ready" },
        validation: { maxLength: 400 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "tender-ready",
      }),
    ],
  },

  // 11 - Existing records & evidence -----------------------------------------
  {
    id: "evidence",
    title: "Existing records & evidence",
    summary:
      "Optional. Bring documents in now or add them later in Evidence - each is filed with its own details.",
    fields: [
      mk({
        id: "evidence.kinds",
        label: "Which records do you already have?",
        help: "We’ll prompt you to file each one (title, category, owner, dates, access level) in Evidence.",
        type: "multiselect",
        options: EVIDENCE_KINDS,
        required: "optional",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "evidence",
      }),
      mk({
        id: "evidence.upload",
        label: "Upload documents (optional)",
        type: "file",
        required: "optional",
        sensitivity: "confidential",
        permissions: OWNER,
        destinationModule: "evidence",
      }),
    ],
  },

  // 12 - Jova preferences ----------------------------------------------------
  {
    id: "jova",
    title: "Jova preferences",
    summary: "Tune how Jova communicates. Its safety guardrails are always on.",
    fields: [
      mk({
        id: "jova.comms_style",
        label: "Preferred communication style",
        type: "select",
        options: COMMS_STYLES,
        required: "optional",
        sensitivity: "low",
        permissions: OWNER_MANAGER,
        destinationModule: "jova",
      }),
      mk({
        id: "jova.explanation_depth",
        label: "Explanation depth",
        type: "select",
        options: EXPLANATION_DEPTH,
        required: "optional",
        sensitivity: "low",
        permissions: OWNER_MANAGER,
        destinationModule: "jova",
      }),
      mk({
        id: "jova.morning_briefing",
        label: "Enable morning briefing",
        type: "boolean",
        required: "optional",
        sensitivity: "low",
        permissions: OWNER_MANAGER,
        destinationModule: "jova",
      }),
      mk({
        id: "jova.briefing_topics",
        label: "Topics to include in briefings",
        type: "multiselect",
        options: BRIEFING_TOPICS,
        required: "optional",
        showIf: { field: "jova.morning_briefing", truthy: true },
        sensitivity: "low",
        permissions: OWNER_MANAGER,
        destinationModule: "jova",
      }),
      mk({
        id: "jova.max_priorities",
        label: "Maximum priorities to show",
        type: "number",
        required: "optional",
        validation: { min: 1, max: 10 },
        sensitivity: "low",
        permissions: OWNER_MANAGER,
        destinationModule: "jova",
      }),
      mk({
        id: "jova.support_types",
        label: "Preferred professional-support types",
        type: "multiselect",
        options: SUPPORT_TYPES,
        required: "optional",
        sensitivity: "low",
        permissions: OWNER_MANAGER,
        destinationModule: "jova",
      }),
      mk({
        id: "jova.understands_not_advice",
        label:
          "I understand Jova provides information and guidance, not professional legal, tax, financial, HR or regulatory advice",
        type: "consent",
        required: "initial",
        sensitivity: "standard",
        permissions: OWNER_MANAGER,
        destinationModule: "jova",
      }),
    ],
  },

  // 13 - Team access ---------------------------------------------------------
  {
    id: "team",
    title: "Team access",
    summary:
      "Invite colleagues now or skip and do it later in Settings → Members.",
    fields: [
      mk({
        id: "team.invites",
        label: "People to invite",
        help: "Name, work email, role and the modules they can access.",
        type: "team_invites",
        required: "optional",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "team",
      }),
    ],
  },

  // 14 - Plan & billing ------------------------------------------------------
  {
    id: "billing",
    title: "Plan & billing",
    summary:
      "Choose a plan. Card details are handled by our payment provider and never stored by Jojan One.",
    fields: [
      mk({
        id: "billing.plan",
        label: "Selected package",
        type: "select",
        options: PLANS,
        required: "progressive",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "billing",
      }),
      mk({
        id: "billing.cycle",
        label: "Billing cycle",
        type: "select",
        options: [
          { value: "monthly", label: "Monthly" },
          { value: "annual", label: "Annual" },
        ],
        required: "optional",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "billing",
      }),
      mk({
        id: "billing.billing_name",
        label: "Billing name",
        type: "text",
        required: "optional",
        validation: { maxLength: 200 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "billing",
      }),
      mk({
        id: "billing.billing_address",
        label: "Billing address",
        type: "address",
        required: "optional",
        validation: { maxLength: 500 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "billing",
      }),
      mk({
        id: "billing.billing_contact",
        label: "Billing contact email",
        type: "email",
        required: "optional",
        validation: { email: true, maxLength: 320 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "billing",
      }),
      mk({
        id: "billing.vat_number",
        label: "VAT number (if applicable)",
        type: "text",
        required: "optional",
        validation: { maxLength: 20 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "billing",
      }),
      mk({
        id: "billing.po_reference",
        label: "Purchase-order reference (optional)",
        type: "text",
        required: "optional",
        validation: { maxLength: 60 },
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "billing",
      }),
      mk({
        id: "billing.card_details",
        label: "Payment card",
        help: "Collected securely by our payment provider at checkout - never entered or stored here.",
        type: "text",
        required: "optional",
        sensitivity: "secret",
        permissions: OWNER,
        destinationModule: "billing",
        neverStore: true,
      }),
      mk({
        id: "billing.accept_subscription",
        label: "I confirm the trial / subscription terms",
        type: "consent",
        required: "progressive",
        sensitivity: "standard",
        permissions: OWNER,
        destinationModule: "billing",
      }),
    ],
  },
];
