/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as TimelineRouteImport } from "./routes/timeline";
import { Route as TenderReadyRouteImport } from "./routes/tender-ready";
import { Route as SimulatorRouteImport } from "./routes/simulator";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as RiskRouteImport } from "./routes/risk";
import { Route as ReportsRouteImport } from "./routes/reports";
import { Route as JovaRouteImport } from "./routes/jova";
import { Route as InvestorReadyRouteImport } from "./routes/investor-ready";
import { Route as HrRouteImport } from "./routes/hr";
import { Route as GovernanceRouteImport } from "./routes/governance";
import { Route as GdprRouteImport } from "./routes/gdpr";
import { Route as ExecutiveRouteImport } from "./routes/executive";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as ContractsRouteImport } from "./routes/contracts";
import { Route as ComplianceRouteImport } from "./routes/compliance";
import { Route as BusinessMapRouteImport } from "./routes/business-map";
import { Route as AcademyRouteImport } from "./routes/academy";
import { Route as IndexRouteImport } from "./routes/index";

const TimelineRoute = TimelineRouteImport.update({
  id: "/timeline",
  path: "/timeline",
  getParentRoute: () => rootRouteImport,
} as any);
const TenderReadyRoute = TenderReadyRouteImport.update({
  id: "/tender-ready",
  path: "/tender-ready",
  getParentRoute: () => rootRouteImport,
} as any);
const SimulatorRoute = SimulatorRouteImport.update({
  id: "/simulator",
  path: "/simulator",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const RiskRoute = RiskRouteImport.update({
  id: "/risk",
  path: "/risk",
  getParentRoute: () => rootRouteImport,
} as any);
const ReportsRoute = ReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => rootRouteImport,
} as any);
const JovaRoute = JovaRouteImport.update({
  id: "/jova",
  path: "/jova",
  getParentRoute: () => rootRouteImport,
} as any);
const InvestorReadyRoute = InvestorReadyRouteImport.update({
  id: "/investor-ready",
  path: "/investor-ready",
  getParentRoute: () => rootRouteImport,
} as any);
const HrRoute = HrRouteImport.update({
  id: "/hr",
  path: "/hr",
  getParentRoute: () => rootRouteImport,
} as any);
const GovernanceRoute = GovernanceRouteImport.update({
  id: "/governance",
  path: "/governance",
  getParentRoute: () => rootRouteImport,
} as any);
const GdprRoute = GdprRouteImport.update({
  id: "/gdpr",
  path: "/gdpr",
  getParentRoute: () => rootRouteImport,
} as any);
const ExecutiveRoute = ExecutiveRouteImport.update({
  id: "/executive",
  path: "/executive",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const ContractsRoute = ContractsRouteImport.update({
  id: "/contracts",
  path: "/contracts",
  getParentRoute: () => rootRouteImport,
} as any);
const ComplianceRoute = ComplianceRouteImport.update({
  id: "/compliance",
  path: "/compliance",
  getParentRoute: () => rootRouteImport,
} as any);
const BusinessMapRoute = BusinessMapRouteImport.update({
  id: "/business-map",
  path: "/business-map",
  getParentRoute: () => rootRouteImport,
} as any);
const AcademyRoute = AcademyRouteImport.update({
  id: "/academy",
  path: "/academy",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/academy": typeof AcademyRoute;
  "/business-map": typeof BusinessMapRoute;
  "/compliance": typeof ComplianceRoute;
  "/contracts": typeof ContractsRoute;
  "/dashboard": typeof DashboardRoute;
  "/executive": typeof ExecutiveRoute;
  "/gdpr": typeof GdprRoute;
  "/governance": typeof GovernanceRoute;
  "/hr": typeof HrRoute;
  "/investor-ready": typeof InvestorReadyRoute;
  "/jova": typeof JovaRoute;
  "/reports": typeof ReportsRoute;
  "/risk": typeof RiskRoute;
  "/settings": typeof SettingsRoute;
  "/simulator": typeof SimulatorRoute;
  "/tender-ready": typeof TenderReadyRoute;
  "/timeline": typeof TimelineRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/academy": typeof AcademyRoute;
  "/business-map": typeof BusinessMapRoute;
  "/compliance": typeof ComplianceRoute;
  "/contracts": typeof ContractsRoute;
  "/dashboard": typeof DashboardRoute;
  "/executive": typeof ExecutiveRoute;
  "/gdpr": typeof GdprRoute;
  "/governance": typeof GovernanceRoute;
  "/hr": typeof HrRoute;
  "/investor-ready": typeof InvestorReadyRoute;
  "/jova": typeof JovaRoute;
  "/reports": typeof ReportsRoute;
  "/risk": typeof RiskRoute;
  "/settings": typeof SettingsRoute;
  "/simulator": typeof SimulatorRoute;
  "/tender-ready": typeof TenderReadyRoute;
  "/timeline": typeof TimelineRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/academy": typeof AcademyRoute;
  "/business-map": typeof BusinessMapRoute;
  "/compliance": typeof ComplianceRoute;
  "/contracts": typeof ContractsRoute;
  "/dashboard": typeof DashboardRoute;
  "/executive": typeof ExecutiveRoute;
  "/gdpr": typeof GdprRoute;
  "/governance": typeof GovernanceRoute;
  "/hr": typeof HrRoute;
  "/investor-ready": typeof InvestorReadyRoute;
  "/jova": typeof JovaRoute;
  "/reports": typeof ReportsRoute;
  "/risk": typeof RiskRoute;
  "/settings": typeof SettingsRoute;
  "/simulator": typeof SimulatorRoute;
  "/tender-ready": typeof TenderReadyRoute;
  "/timeline": typeof TimelineRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/academy"
    | "/business-map"
    | "/compliance"
    | "/contracts"
    | "/dashboard"
    | "/executive"
    | "/gdpr"
    | "/governance"
    | "/hr"
    | "/investor-ready"
    | "/jova"
    | "/reports"
    | "/risk"
    | "/settings"
    | "/simulator"
    | "/tender-ready"
    | "/timeline";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/academy"
    | "/business-map"
    | "/compliance"
    | "/contracts"
    | "/dashboard"
    | "/executive"
    | "/gdpr"
    | "/governance"
    | "/hr"
    | "/investor-ready"
    | "/jova"
    | "/reports"
    | "/risk"
    | "/settings"
    | "/simulator"
    | "/tender-ready"
    | "/timeline";
  id:
    | "__root__"
    | "/"
    | "/academy"
    | "/business-map"
    | "/compliance"
    | "/contracts"
    | "/dashboard"
    | "/executive"
    | "/gdpr"
    | "/governance"
    | "/hr"
    | "/investor-ready"
    | "/jova"
    | "/reports"
    | "/risk"
    | "/settings"
    | "/simulator"
    | "/tender-ready"
    | "/timeline";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AcademyRoute: typeof AcademyRoute;
  BusinessMapRoute: typeof BusinessMapRoute;
  ComplianceRoute: typeof ComplianceRoute;
  ContractsRoute: typeof ContractsRoute;
  DashboardRoute: typeof DashboardRoute;
  ExecutiveRoute: typeof ExecutiveRoute;
  GdprRoute: typeof GdprRoute;
  GovernanceRoute: typeof GovernanceRoute;
  HrRoute: typeof HrRoute;
  InvestorReadyRoute: typeof InvestorReadyRoute;
  JovaRoute: typeof JovaRoute;
  ReportsRoute: typeof ReportsRoute;
  RiskRoute: typeof RiskRoute;
  SettingsRoute: typeof SettingsRoute;
  SimulatorRoute: typeof SimulatorRoute;
  TenderReadyRoute: typeof TenderReadyRoute;
  TimelineRoute: typeof TimelineRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/timeline": {
      id: "/timeline";
      path: "/timeline";
      fullPath: "/timeline";
      preLoaderRoute: typeof TimelineRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/tender-ready": {
      id: "/tender-ready";
      path: "/tender-ready";
      fullPath: "/tender-ready";
      preLoaderRoute: typeof TenderReadyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/simulator": {
      id: "/simulator";
      path: "/simulator";
      fullPath: "/simulator";
      preLoaderRoute: typeof SimulatorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/risk": {
      id: "/risk";
      path: "/risk";
      fullPath: "/risk";
      preLoaderRoute: typeof RiskRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reports": {
      id: "/reports";
      path: "/reports";
      fullPath: "/reports";
      preLoaderRoute: typeof ReportsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/jova": {
      id: "/jova";
      path: "/jova";
      fullPath: "/jova";
      preLoaderRoute: typeof JovaRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/investor-ready": {
      id: "/investor-ready";
      path: "/investor-ready";
      fullPath: "/investor-ready";
      preLoaderRoute: typeof InvestorReadyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/hr": {
      id: "/hr";
      path: "/hr";
      fullPath: "/hr";
      preLoaderRoute: typeof HrRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/governance": {
      id: "/governance";
      path: "/governance";
      fullPath: "/governance";
      preLoaderRoute: typeof GovernanceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/gdpr": {
      id: "/gdpr";
      path: "/gdpr";
      fullPath: "/gdpr";
      preLoaderRoute: typeof GdprRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/executive": {
      id: "/executive";
      path: "/executive";
      fullPath: "/executive";
      preLoaderRoute: typeof ExecutiveRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/contracts": {
      id: "/contracts";
      path: "/contracts";
      fullPath: "/contracts";
      preLoaderRoute: typeof ContractsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/compliance": {
      id: "/compliance";
      path: "/compliance";
      fullPath: "/compliance";
      preLoaderRoute: typeof ComplianceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/business-map": {
      id: "/business-map";
      path: "/business-map";
      fullPath: "/business-map";
      preLoaderRoute: typeof BusinessMapRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/academy": {
      id: "/academy";
      path: "/academy";
      fullPath: "/academy";
      preLoaderRoute: typeof AcademyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRoute,
  BusinessMapRoute: BusinessMapRoute,
  ComplianceRoute: ComplianceRoute,
  ContractsRoute: ContractsRoute,
  DashboardRoute: DashboardRoute,
  ExecutiveRoute: ExecutiveRoute,
  GdprRoute: GdprRoute,
  GovernanceRoute: GovernanceRoute,
  HrRoute: HrRoute,
  InvestorReadyRoute: InvestorReadyRoute,
  JovaRoute: JovaRoute,
  ReportsRoute: ReportsRoute,
  RiskRoute: RiskRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  TenderReadyRoute: TenderReadyRoute,
  TimelineRoute: TimelineRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
